CREATE TABLE IF NOT EXISTS Users
(
	id SERIAL PRIMARY KEY NOT NULL,
	firstName CHARACTER VARYING(30) NOT NULL,
	lastName CHARACTER VARYING(30) NOT NULL,
	email CHARACTER VARYING(30),
	birthdate DATE,
	age SMALLINT,
	budget REAL,
	status BOOLEAN
);